apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-service
  namespace: vote-namespace
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - name: 5002-80
    nodePort: 31001
    port: 5002
    protocol: TCP
    targetPort: 80
  selector:
    app: result