# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: result
#   name: result-deployment
#   namespace: vote-namespace
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: result
#   template:
#     metadata:
#       labels:
#         app: result
#     spec:
#       containers:
#       - image: wjma90/examplevotingapp_result:before
#         name: result
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-deployment
  namespace: vote-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: wjma90/examplevotingapp_result:before
        name: result
        ports:
        - containerPort: 80
        env:
        - name: PGHOST
          value: "db"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: ""
