apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-service
  namespace: vote-namespace
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - name: 5001-80
    nodePort: 31000
    port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    app: vote