# a.votedeploymentCreateadeployment:name='vote-deployment'image='wjma90/examplevotingapp_vote:before'

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-deployment
  namespace: vote-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: wjma90/examplevotingapp_vote:before
        name: vote
        ports:
        - containerPort: 80
